apiVersion: v1
kind: Service
metadata:
  name: #{Octopus.Project.Slug}-service
spec:
  type: ClusterIP
  selector:
    component: #{Octopus.Project.Slug}-service
  ports:
    - port: 80
      targetPort: 80
